#!/bin/sh

do_mount() {
	local hostdir="$(git rev-parse --show-toplevel)/$1"
	while read x; do
		mkdir -p "$hostdir/$x"
		sudo mount --bind "$x" "$hostdir/$x"
	done
}

do_umount() {
	local hostdir="$(git rev-parse --show-toplevel)/$1"
	while read x; do
		sudo umount "$hostdir/$x"
	done
}

do_rm() {
	local hostdir="$(git rev-parse --show-toplevel)/$1"
	if find "$hostdir" -type d | grep -F -f- /etc/mtab; then
		echo "abort: umount the above mountpoints first";
		return 1
	fi
	git ls-tree --name-only -r HEAD "$hostdir" | xargs -n1 rm
}

cmd="do_mount host"
case "$1" in
-u )	cmd="do_umount host";;
-r )	cmd="do_rm host";;
esac

cat << EOF | $cmd
/etc/apache2/sites-available/
/usr/local/bin/
/var/www/occupywiki.org.uk/
/var/lib/occupywiki.org.uk/
EOF
