<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "OccupyWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/w";
$wgScriptExtension  = ".php";

# Config for nice URL's
$wgScript = "$wgScriptPath/index.php";
$wgRedirectScript = "$wgScriptPath/redirect.php";
$wgUsePathInfo = true;
$wgArticlePath = "/wiki/$1";
# actions we want to generate short URLs for
$actions = array(
  #'watch', # can't use this with Gadget extension, see https://bugzilla.wikimedia.org/show_bug.cgi?id=27146
  #'unwatch',
  'delete',
  # 'revert', # seems to be no longer used
  # 'rollback', # pointless since needs token to work
  'protect',
  'unprotect',
  # 'markpatrolled', # pointless since needs token to work
  'render',
  'purge',
  'submit',
  'edit',
  'history',
  'historysubmit',
  'ajax',
  'credits',
);
foreach ( $actions as $action ) {
  $wgActionPaths[$action] = "/$action/$1";
}

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgScriptPath/images/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "wiki@occupywiki.org.uk";
$wgPasswordSender = "wiki@occupywiki.org.uk";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
/* see AdminSettings.php */

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

# Maximum amount of virtual memory available to shell processes under linux, in KB.
# The default setting of 102400 is too low to generate thumbnals for some SVG images.
$wgMaxShellMemory = 204800;

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

# http://www.mediawiki.org/wiki/Manual:$wgDefaultSkin
## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = 'vector';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://creativecommons.org/licenses/publicdomain/";
$wgRightsText = "Public Domain";
$wgRightsIcon = "${wgScriptPath}/skins/common/images/public-domain.png";
# $wgRightsCode = "pd"; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );
# file types for uploads
$wgUploadSizeWarning = 6000 * 3000;
#$wgMimeDetectorCommand = "file -bi";
#$wgVerifyMimeType = false;
$wgFileExtensions = array( 'avi', 'mp3', 'rm', 'mpg', 'mpeg', 'mp4', 'svg', 'png', 'gif', 'jpg', 'jpeg', 'pdf', 'rtf', 'doc', 'txt', 'ppt', 'odp', 'odc', 'odf', 'odg', 'odi', 'odif', 'odm', 'ods', 'odt', 'otc', 'otf', 'otg', 'oth', 'oti', 'otp', 'ots', 'ott', 'psd', 'ai', 'eps', 'tif','dwg');


# No anonymous editing allowed -
$wgGroupPermissions['*']['edit'] = false;

# allow users to be banned
$wgSysopUserBans = true;

# spambot
$wgSpamRegex="/overflow:.*auto|display:.*none|wifiguide.org/";

# Enable subpages in the main namespace
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Manual:$wgNamespacesWithSubpages#Enabling_for_a_namespace
$wgNamespacesWithSubpages[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_PROJECT] = true;

# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Manual:$wgAllowCopyUploads
#$wgGroupPermissions['sysops']['upload_by_url'] = true;
#$wgAllowCopyUploads = true;

# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:UploadWizard
#$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = /usr/bin/convert;
#
#require_once( "$IP/extensions/UploadWizard/UploadWizard.php" );

# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:Widgets
require_once("$IP/extensions/Widgets/Widgets.php");
$wgGroupPermissions['sysop']['editwidgets'] = true;

# ParserFunctions
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:ParserFunctions
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );

# Validator
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:Validator 
require_once( "$IP/extensions/Validator/Validator.php" );

# Maps
# http://mapping.referata.com/wiki/Help:Installation
require_once( "$IP/extensions/Maps/Maps.php" );

# AntiBot
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:AntiBot
require_once( "$IP/extensions/AntiBot/AntiBot.php" );

# AbuseFilter
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:AbuseFilter
require_once( "$IP/extensions/AbuseFilter/AbuseFilter.php" );

# AntiSpoof
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:AntiSpoof
require_once( "$IP/extensions/AntiSpoof/AntiSpoof.php" );

# SimpleAntiSpam
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:SimpleAntiSpam
require_once("$IP/extensions/SimpleAntiSpam/SimpleAntiSpam.php");

# SpamBlacklist
# https://secure.wikimedia.org/wikipedia/mediawiki/wiki/Extension:SpamBlacklist
# Bump the Perl Compatible Regular Expressions backtrack memory limit
# (PHP 5.2.x default, 100K, is too low for SpamBlacklist)
#ini_set( 'pcre.backtrack_limit', '8M' );
#require_once( "$IP/extensions/SpamBlacklist/SpamBlacklist.php" );

# UserMerge
require_once( "$IP/extensions/UserMerge/UserMerge.php" );
$wgGroupPermissions['bureaucrat']['usermerge'] = true;

# UserDrop
require_once( "$IP/extensions/UserDrop/UserDrop.php" );
$wgGroupPermissions['bureaucrat']['userdrop'] = true;

# ConfirmEdit
require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php");
require_once( "$IP/extensions/ConfirmEdit/ReCaptcha.php");
$wgCaptchaClass = 'ReCaptcha';
/* see AdminSettings.php */
//$wgReCaptchaPublicKey = 0;
//$wgReCaptchaPrivateKey = 0;
$wgCaptchaTriggers['addurl'] = false; // temporary measure on request

# ReplaceText, for renaming categories
require_once( "$IP/extensions/ReplaceText/ReplaceText.php" );
// thought about this but probably best to not restrict
//$wgGroupPermissions['bureaucrat']['replacetext'] = true;
//$wgGroupPermissions['sysop']['replacetext'] = false;

# Gadgets
// HotCat not working so disable for now
require_once( "$IP/extensions/Gadgets/Gadgets.php" );

# Interwiki

require_once("$IP/extensions/Interwiki/Interwiki.php");
$wgGroupPermissions['*']['interwiki'] = false;
$wgGroupPermissions['bureaucrat']['interwiki'] = true;

# CategoryTree

require_once("$IP/extensions/CategoryTree/CategoryTree.php");
$wgEnableMWSuggest = true;

# misc settings

//$wgShowExceptionDetails = true;
$wgAllowUserCss = true;

/* this must be at the bottom */
require_once( "AdminSettings.php" );

?>
